services:
  # Simulador de AWS RDS para pruebas locales
  db:
    image: postgres:15
    container_name: simi_postgres_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: simi_pass123
      POSTGRES_DB: simi_erp_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - simi-net

  frontend:
    build:
      context: ./frontend
    container_name: simi_frontend_local
    ports:
      - "80:80"
    environment:
      - DB_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=simi_pass123
      - POSTGRES_DB=simi_erp_db
      - JWT_SECRET=simi_clave_secreta_mfa
    depends_on:
      - db
    networks:
      - simi-net

networks:
  simi-net:
    driver: bridge