services:
  frontend:
    build:
      context: ./frontend
    container_name: simi_frontend
    ports:
      - "80:80"
    environment:
      - DB_HOST=${DB_HOST}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=simi_clave_secreta_mfa
    networks:
      - simi-net

networks:
  simi-net:
    driver: bridge